### PR TITLE
Add support for parsing environment variables in the YAML file

### PR DESCRIPTION
**Pull request by alexlance**
With this patch simple bash variables can be placed in the YAML file and they will be substituted with their environment value. The variables need to be in this format: ${VAR}

### CODE REVIEW

**Comment by vaab** [comment]
Hi, thank you for you interest, and sorry for the delay in my answer.

Can you be more specific about what you are trying to handle ?, for instance by providing a quick example of how to use it (which then could be used as a seed for some doc section in the ``README.md``, if this PR is to be included). I can surely infer parts of it through reading the code, but this is exactly why I didn't answer right away. 

And in your case, code might not reflect your intention (I mean that there are indeed some strange behavior that might be... bugs).

So here's my go about what I've understood is your intention...

Your PR proposes to add an implicit parser (which means no special YAML markup will have to be used) to allow parsing all values for files that match this syntax ``${MYVAR}``.

The part that is not clear is about if the whole value should match only one variable. If not why are you using ``^`` in your regexp to force match at the beginning. 
But if this was your intent, why not use ``$`` at the end of the regex to force match at the end ? Your actual code matches only variables at the start.

This example puts in light these incoherences (I´ve reordered the actual output lines to have better readability):

```
cat <<EOF | shyaml get-value
canonical-use: ${PWD}
unspecified-use: $PWD
bogus-1: this one is not replaced --> ${PWD}
bogus-2: ${PWD} <-- this one is replaced
more-bogus-1: ${PWD
more-bogus-2: $PWD}
EOF
canonical-use: /home/vaab/dev/python/shyaml
unspecified-use: /home/vaab/dev/python/shyaml
bogus-1: this one is not replaced --> ${PWD}
bogus-2: /home/vaab/dev/python/shyaml <-- this one is replaced
more-bogus-1: /home/vaab/dev/python/shyaml
more-bogus-2: /home/vaab/dev/python/shyaml
```

Besides implementation issues or specification incoherence at this stage - which could be corrected - I'm not convinced that we should add some special transformation behavior to parsing YAML: A lot of people uses ``shyaml`` and YAML is used to store very different values. In particular, in most cases, people don't want to see their text-values containing ``${MYVAR}`` transformed in any case at parse time. Besides, no magic is expected on the yaml side, it just have to carry data, and not transform it.

You can achieve the same desired result for your case by using ``shyaml`` to read the data, then parse it the way you want in your script. For instance you could easily use ``eval`` to force the interpretation of ``${MYVAR}``.

I'll close this PR for now, but if you feel I missed the point or that you have convincing arguments to include this in ``shyaml``, feel free to comment and/or reopen.

Finally, for your own usage, it you wish to use your code in your project (even that I won't encourage you for simple separation of concerns and maintenability of your own code regarding evolution of the main package), you should be concerned by

**Comment by vaab** [comment]
What could make sense however is an explicit way to declare and use transformation plugins. This would allow to declare on the command line of shyaml (or with other ways) some transformation plugin related to explicit tag or regexp (implicit tag). In this way we avoid hard-coding some transformations, and allow to propose various plugins.

This would require more than a few lines of code, but I will surely consider it for an inclusion.

**Comment by alexlance** [comment]
> The part that is not clear is about if the whole value should match only one variable. If not why are 
> you using  ^  in your regexp to force match at the beginning.

But in this PR, the regex does *not* bind to the start of the match using ^.

    git show 9109178 | grep '\^'

And so I cannot replicate the error that you're experiencing. Although bash is complaining about a syntax error with the more-bogus-1 and more-bogus-2 examples you've written.

All good, if you'd prefer not to merge this pull request. Thought it might have been useful for you or others.

**Comment by vaab** [comment]
My bad for the poor example. I pasted it in cat heredoc style so you could copy&paste in one go, but I actually had crafted a file myself. I forgotten that hererdoc in bash will interpret variables... ;)

So copy paste this in a file named ``test.yaml``
```
canonical-use: ${PWD}
unspecified-use: $PWD
bogus-1: this one is not replaced --> ${PWD}
bogus-2: ${PWD} <-- this one is replaced
bogus-3: $X this one is now replaced --> ${PWD}
more-bogus-1: ${PWD
more-bogus-2: $PWD}
```

Then execute this:

    cat test.yaml | shyaml get-value

To get (with the exception of line order):

```
canonical-use: /home/vaab/dev/python/shyaml
unspecified-use: /home/vaab/dev/python/shyaml
bogus-1: this one is not replaced --> ${PWD}
bogus-2: /home/vaab/dev/python/shyaml <-- this one is replaced
bogus-3: ' this one is now replaced --> /home/vaab/dev/python/shyaml'
more-bogus-1: /home/vaab/dev/python/shyaml
more-bogus-2: /home/vaab/dev/python/shyaml
```

So this illustrate well the issues. And you are right about the ``^``... thought I had seen it. But then I can't explain why we actually get all this inconsistences :-)

And I understand that you want to share something that was useful at first for your use case, but I really have to think to the general case, and a large majority of users would have been hit by a lot of strange bugs (I'm not speaking of the bugs up there, but the fact that a lot of people work with other things than bash code containing variable that as to be expanded upon parsing without way to disable it.)

Anyway, your patch is saved in google's memory, and it might help some people. And as I stated in previous message, this idea, if explicit and optional (and easily expandable) is for me valid for inclusion.

**Pull request closed without merging**
