### PR TITLE
Non-expert fix for UnicodeEncodeError

### PR DESCRIPTION
**Pull request by szepeviktor**
in a subshell
Fixes: #35

### CODE REVIEW

**Comment by szepeviktor** [comment]
Maybe using double quotes would appropriate.

**Comment by szepeviktor** [comment]
@vaab Could you review this one?

**Comment by vaab** [comment]
Hm, this is not a nice fix. We need to support other encodings. So, the best is probably to correct it only for system that has a problem: python 2 namely.

The problem is that when it is not a TTY and that ``PYTHONIOENCODING`` is not set when python starts up, then ``sys.stdout.encoding`` doesn't get a proper value. We need to explicitely encode the string ourselves then.
The encoding we will find will have to be a sensible default which ``local.getpreferredencoding()`` seems to be.

**Comment by szepeviktor** [comment]
Thank you!
```
echo $(PYTHONIOENCODING="utf_8" shyaml get-value system.trespass-warning < server.yml)
```

**Pull request closed without merging**
