### PR TITLE
Introduce conformant pycodestyle

### PR DESCRIPTION
**Pull request by szepeviktor**
@vaab Reborn #44

### CODE REVIEW

**Comment by szepeviktor** [comment]
For `E722 do not use bare 'except'` we have two ways:

1. change to `except TypeError:`
1. ignore it: `ignore = E266,E722`

**Comment by szepeviktor** [comment]
@vaab Could you decide on the last finding?

**Comment by vaab** [comment]
Hi, I have had a look to your changes and I'm integrating them with some minor exception (and I solved the pycodestyle warning about ``except`` by catching ``except Exception``). I'm not willing to integrate the conformity check in travis tests however. I understand that this is a perfectly valid way to do it, but I do want to separate concerns here. The conformity tests do not need to be checked on each platform and they have their place in other tests that I have on my end and that are run prior to any platform tests.

**Comment by vaab** [comment]
Is it all okay for you ? Feel free to re-open if there's anything that I missed.

**Comment by vaab** [comment]
Well, you should consider not mixing style check with test check in your CI. You are wasting time, computer power and energy, and it is inefficient. There are no reason to check the style in your platform matrix (your python style is good or not, this should not be tested over and over on windows, linux, python 2.7, 3.4, 3.5 ...). I'm not saying you should not put some style checks... I use and have used flake8, pep8 (old name of pycodestyle), pycheckers, pylint... . They have their place in CI, or pre-commit as I do, where you are coding (in your editor preferably, as you type)... I don't want to run full tests to have the result of coding style checking come so late, they should be instant. If you want absolutely in a external CI loop, there are probably other webservices than travis that will do this check... once.

In travis hooks, you are doing it wrong, IMHO. But diversity of view is interesting, and if you have argumented views on why putting it in travis is a good idea (it is NOT a very bad idea, it is just not good enough in my settings for the reason given before), I'm very happy to hear your arguments.

**Pull request closed without merging**
